source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SWImagePickerManager_Example' do
  pod "SWImagePickerManager", :path => "../"

  target 'SWImagePickerManager_Tests' do
    inherit! :search_paths
  end
end
