source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SWImagePickerManager_Example', :exclusive => true do
  pod "SWImagePickerManager", :path => "../"
end

target 'SWImagePickerManager_Tests', :exclusive => true do
  pod "SWImagePickerManager", :path => "../"

  
end
